language: c++
os: linux
dist: focal

jobs:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
      addons: &linuxaddons
        apt:
          packages: &packages
            - automake
            - libboost-all-dev
            - libcurl4-openssl-dev
            - g++-10

    - os: linux
      arch: arm64
      compiler: gcc
      addons: *linuxaddons

script:
  - |
    ./bootstrap
    CC=gcc-10 CXX=g++-10 ./configure
    make
  - |
    sudo apt-get install libmagickwand-dev
    ./bootstrap
    CC=gcc-10 CXX=g++-10 ./configure
    make

