language: c++
sudo: required
dist: xenial

addons: &addons
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
    packages: &packages
      - automake
      - libboost1.58-all-dev
      - libcurl4-openssl-dev
      - gcc-9
      - g++-9

compiler:
  - gcc

script:
  - |
    ./bootstrap
    CC=gcc-9 CXX=g++-9 ./configure
    make
  - |
    sudo apt-get install libmagickwand-dev
    ./bootstrap
    CC=gcc-9 CXX=g++-9 ./configure
    make

